path: e:/Dataset/dataset/yolo_obb_non_frame
train: images/train
val: images/val
test: images/test
nc: 31
names:
  - "-"
  - "/"
  - "0"
  - "00"
  - "1"
  - "2"
  - "22"
  - "3"
  - "4"
  - "44"
  - "5"
  - "6"
  - "7"
  - "8"
  - "88"
  - "9"
  - "A"
  - "B"
  - "C"
  - "D"
  - "E"
  - "F"
  - "G"
  - "H"
  - "O"
  - "T"
  - "U"
  - "W"
  - "X"
  - "Y"
  - "x"
