path: ./dataset_stage2_obb
train: images/train
val: images/val
test: images/test

nc: 18
names:
  0: 0
  1: 1
  2: 2
  3: 3
  4: 4
  5: 5
  6: 6
  7: 7
  8: 8
  9: 9
  10: B
  11: C
  12: D
  13: G
  14: H
  15: S
  16: W
  17: X
